include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
    - '/integration_test'
    - '/test_driver'

linter:
  rules:
    library_private_types_in_public_api: false