name: flutter_bdd
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_mobx: ^2.0.6+5
  flutter_modular: ^5.0.3
  mobx: ^2.1.4
  path_provider: ^2.0.13

dev_dependencies:
  
  build_runner: ^2.3.3
  flutter_gherkin: ^3.0.0-rc.17
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mobx_codegen: ^2.1.1
  very_good_analysis: ^4.0.0+1


flutter:
  uses-material-design: true

